# .github/workflows/dev.yaml
name: 'Terraform - eks-dev'
on: [workflow_dispatch]

permissions:
  id-token: write # need this for OIDC  
  contents: read

jobs: 
  plan:
    name: Plan
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: '/home/runner/work/eks-tfvars'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::647712509431:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
  
     # - name: "Get Application Token"
     #   id: get_app_token
     #   uses: tibdex/github-app-token@v1
     #   with:
     #    app_id: ${{ secrets.EKS_DEV_APP_CLIENTID  }}
      #    private_key: ${{ secrets.EKS_DEV_APP_SECRET }}
      #- name: Extend Git credentials
      #  uses: de-vri-es/setup-git-credentials@v2.0.10
      #  with:
      #   credentials: https://user:${{ steps.get_app_token.outputs.token }}@github.com
      - name: get-token    
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.EKS_DEV_APP_SECRET }}
          app-id: ${{ secrets.EKS_DEV_APP_CLIENTID  }}

      - name: Check out code which have EKS terraform resource file
        uses: actions/checkout@v2
        with:
          repository: vishal267/jn-eks
          token: ${{ steps.get-token.outputs.token }}
      - name: List files in directory 
        run: ls -l /home/runner/work/eks-tfvars
      - name: Terraform init 
        run:  cd terraform/resources/eks; terraform init
      - name: Terraform plan  
        run:  cd terraform/resources/eks; terraform plan  -var-file=/home/runner/work/thejn-dev/thejn-dev/terraform/resources/eks-dev/variables.tfvars
      
